version: '3.8'

services:
  translation-service:
    build: .
    ports:
      - "7888:7888"
    environment:
      - ENV=production
    volumes:
      - ./temp:/app/temp  # For temporary files
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7888"]
      interval: 30s
      timeout: 10s
      retries: 3
