services:
  translation-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: word-translation-service
    ports:
      - "7888:7888"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512
      - OMP_NUM_THREADS=4
      - STANZA_RESOURCES_DIR=/root/stanza_resources
      - ENV=production
    volumes:
      # Mount cache directory for stanza models
      - ./cache:/app/cache
      # Mount stanza models from host machine
      - /mnt/c/Users/admin/stanza_resources:/root/stanza_resources
      # Mount for temporary files
      - translation_temp:/tmp
    gpus: all
    restart: always
    networks:
      - translate
    shm_size: 8g

volumes:
  translation_temp:
    driver: local

networks:
  translate:
    name: translate
    external: true
    driver: bridge
